spring.application.name=polizas

# H2 en memoria
spring.datasource.url=jdbc:h2:mem:polizasdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
# Necesario para que Hibernate cree las tablas ANTES de que se ejecute data.sql
spring.jpa.defer-datasource-initialization=true

# Regla de negocio: incremento de IPC aplicado en renovaciones (5%)
poliza.ipc=0.05

# Seguridad
api.security.key=123456

# URL del mock del CORE (Adapter)
core.mock.url=http://localhost:8080/core-mock/evento